---
- hosts: elk.my
  become: yes
  tasks:
    - name: Download zabbix repo package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb"
        dest: /tmp/zabbix.deb
    - name: Install zabbix repo
      apt:
        deb: /tmp/zabbix.deb
        state: present
    - name: Install zabbix agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes
    - name: Stop service zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
    - name: Remove zabbix config 
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent
    - name: Create new zabbix config file from template
      template:
        src: /etc/ansible/common/files/ubuntu_zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
    - name: Start service zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
