---
- hosts: all
  become: yes
  tasks:
    - name: Download zabbix repo package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
        dest: /tmp/zabbix.deb
      when: ansible_os_family == "Debian"
    - name: Install zabbix repo
      apt:
        deb: /tmp/zabbix.deb
        state: present
      when: ansible_os_family == "Debian"
    - name: Install zabbix agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Stop service zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
      when: ansible_os_family == "Debian"
    - name: Remove zabbix config file
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent
      when: ansible_os_family == "Debian"
    - name: Create new zabbix config file from template
      template:
        src: /etc/ansible/common/files/ubuntu_zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
      when: ansible_os_family == "Debian"
    - name: install zabbix centOS 7 rpm file
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-agent-6.0.0-1.el7.x86_64.rpm
        validate_certs: no
      when: ansible_os_family == "RedHat"
    - name: upgrade all packages
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
    - name: install zabbix-agent 6.x for centOS 7
      yum:
        name: zabbix-agent
        state: latest
      when: ansible_os_family == "RedHat"
    - name: Copy zabbix_agentd.conf file with owner and permissions
      ansible.builtin.copy:
        src: /etc/ansible/common/files/centos_zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
      when: ansible_os_family == "RedHat"
    - name: Start service Zabbix Agent
      ansible.builtin.service:
        name: zabbix-agent
        state: started
        enabled: yes  
